# Assignment 19R11A05K0 Varun Veesamshetty

## Fish Dataset Multi Linear Regression

In [1]:
import pandas as pd
import numpy as np
np

<module 'numpy' from 'C:\\Users\\Varun\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [2]:
ds=pd.read_csv("Fish.csv")

In [3]:
ds

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5     Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6     Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7     Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8     Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9     Bream   500.0     28.5     30.7     36.2  14.2266  4.9594
10    Bream   475.0     28.4     31.0     36.2  14.2628  5.1042
11    Bream   500.0     28.7     31.0     36.2  14.3714  4.8146
12    Bream   500.0     29.1     31.5     36.4  13.7592  4.3680
13    Bream   340.0     29.5     32.0     37.3  13.9129  5.0728
14    Bream   600.0     29.4     32.0     37.2  14.9544  5.1708
15    Bream   600.0     29.4     32.0     37.2  15.4380  5.5800
16    Bream   700.0     30.4     33.0     38.3  14.8604  5.2854
17    Bream   700.0     30.4     33.0     38.5  14.9380  5.1975
18    Bream   610.0     30.9     33.5     38.6  15.6330  5.1338
19    Bream   650.0     31.0     33.5     38.7  14.4738  5.7276
20    Bream   575.0     31.3     34.0     39.5  15.1285  5.5695
21    Bream   685.0     31.4     34.0     39.2  15.9936  5.3704
22    Bream   620.0     31.5     34.5     39.7  15.5227  5.2801
23    Bream   680.0     31.8     35.0     40.6  15.4686  6.1306
24    Bream   700.0     31.9     35.0     40.5  16.2405  5.5890
25    Bream   725.0     31.8     35.0     40.9  16.3600  6.0532
26    Bream   720.0     32.0     35.0     40.6  16.3618  6.0900
27    Bream   714.0     32.7     36.0     41.5  16.5170  5.8515
28    Bream   850.0     32.8     36.0     41.6  16.8896  6.1984
29    Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
..      ...     ...      ...      ...      ...      ...     ...
129    Pike   300.0     31.7     34.0     37.8   5.7078  4.1580
130    Pike   300.0     32.7     35.0     38.8   5.9364  4.3844
131    Pike   300.0     34.8     37.3     39.8   6.2884  4.0198
132    Pike   430.0     35.5     38.0     40.5   7.2900  4.5765
133    Pike   345.0     36.0     38.5     41.0   6.3960  3.9770
134    Pike   456.0     40.0     42.5     45.5   7.2800  4.3225
135    Pike   510.0     40.0     42.5     45.5   6.8250  4.4590
136    Pike   540.0     40.1     43.0     45.8   7.7860  5.1296
137    Pike   500.0     42.0     45.0     48.0   6.9600  4.8960
138    Pike   567.0     43.2     46.0     48.7   7.7920  4.8700
139    Pike   770.0     44.8     48.0     51.2   7.6800  5.3760
140    Pike   950.0     48.3     51.7     55.1   8.9262  6.1712
141    Pike  1250.0     52.0     56.0     59.7  10.6863  6.9849
142    Pike  1600.0     56.0     60.0     64.0   9.6000  6.1440
143    Pike  1550.0     56.0     60.0     64.0   9.6000  6.1440
144    Pike  1650.0     59.0     63.4     68.0  10.8120  7.4800
145   Smelt     6.7      9.3      9.8     10.8   1.7388  1.0476
146   Smelt     7.5     10.0     10.5     11.6   1.9720  1.1600
147   Smelt     7.0     10.1     10.6     11.6   1.7284  1.1484
148   Smelt     9.7     10.4     11.0     12.0   2.1960  1.3800
149   Smelt     9.8     10.7     11.2     12.4   2.0832  1.2772
150   Smelt     8.7     10.8     11.3     12.6   1.9782  1.2852
151   Smelt    10.0     11.3     11.8     13.1   2.2139  1.2838
152   Smelt     9.9     11.3     11.8     13.1   2.2139  1.1659
153   Smelt     9.8     11.4     12.0     13.2   2.2044  1.1484
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
ds.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [5]:
x=ds.drop(['Weight'] , axis = 1).values

In [6]:
x

array([['Bream', 23.2, 25.4, 30.0, 11.52, 4.02],
       ['Bream', 24.0, 26.3, 31.2, 12.48, 4.3056],
       ['Bream', 23.9, 26.5, 31.1, 12.3778, 4.6961],
       ['Bream', 26.3, 29.0, 33.5, 12.73, 4.4555],
       ['Bream', 26.5, 29.0, 34.0, 12.444, 5.1339999999999995],
       ['Bream', 26.8, 29.7, 34.7, 13.6024, 4.9274],
       ['Bream', 26.8, 29.7, 34.5, 14.1795, 5.2785],
       ['Bream', 27.6, 30.0, 35.0, 12.67, 4.69],
       ['Bream', 27.6, 30.0, 35.1, 14.0049, 4.8438],
       ['Bream', 28.5, 30.7, 36.2, 14.2266, 4.9594],
       ['Bream', 28.4, 31.0, 36.2, 14.2628, 5.1042],
       ['Bream', 28.7, 31.0, 36.2, 14.3714, 4.8146],
       ['Bream', 29.1, 31.5, 36.4, 13.7592, 4.368],
       ['Bream', 29.5, 32.0, 37.3, 13.9129, 5.0728],
       ['Bream', 29.4, 32.0, 37.2, 14.9544, 5.1708],
       ['Bream', 29.4, 32.0, 37.2, 15.437999999999999, 5.58],
       ['Bream', 30.4, 33.0, 38.3, 14.8604, 5.2854],
       ['Bream', 30.4, 33.0, 38.5, 14.937999999999999, 5.1975],
       ['Bream', 30.9, 33.5,

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer( [("encoder" , OneHotEncoder() ,[0] )] , remainder = "passthrough")
x = ct.fit_transform(x)

In [8]:
x

array([[1.0, 0.0, 0.0, ..., 30.0, 11.52, 4.02],
       [1.0, 0.0, 0.0, ..., 31.2, 12.48, 4.3056],
       [1.0, 0.0, 0.0, ..., 31.1, 12.3778, 4.6961],
       ...,
       [0.0, 0.0, 0.0, ..., 13.8, 2.2769999999999997, 1.2558],
       [0.0, 0.0, 0.0, ..., 15.2, 2.8728, 2.0672],
       [0.0, 0.0, 0.0, ..., 16.2, 2.9322, 1.8792]], dtype=object)

In [9]:
y = ds.iloc[:,1].values

In [10]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

In [11]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split( x , y , test_size = 0.2 , random_state = 10000 )

In [12]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
ypred = mlr.predict(x_test)

In [14]:
ypred

array([ 718.06721366,  712.57810095,  887.30510826, 1426.75279735,
        680.85725697,  808.42966591,  168.09223184,  108.83912825,
        185.2044695 ,  237.6374358 ,  430.72122646,  258.63583313,
        115.92678652,  196.37995379,  861.38826403,  413.7019005 ,
         32.64882712,  944.28168493,  131.0688483 ,  720.72605822,
        626.05939662,  989.39507303,  634.06562714,  536.43981038,
        -10.76055962,  204.11508289,  982.51619746,  482.74166561,
        956.105739  ,  257.18803764,   10.78276011,  859.36964596])

In [15]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [16]:
accuracy

0.9381871771286753

In [17]:
yp=mlr.predict(ct.transform( [["Bream" , 24, 25, 30, 11, 4]] ))

In [18]:
yp

array([215.1524474])

## Bank Dataset Logistic Regression

In [19]:
ds1 = pd.read_csv("bank.csv")

In [20]:
ds1

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [21]:
ds1.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds1=ds1.apply(LabelEncoder().fit_transform)


In [23]:
x=ds1.iloc[:,0:16].values
y=ds1.iloc[:,16].values

In [24]:
x

array([[ 41,   0,   1, ...,   0,   0,   3],
       [ 38,   0,   1, ...,   0,   0,   3],
       [ 23,   9,   1, ...,   0,   0,   3],
       ...,
       [ 14,   9,   2, ...,   0,   0,   3],
       [ 25,   9,   1, ..., 155,   5,   0],
       [ 16,   9,   1, ...,   0,   0,   3]], dtype=int64)

In [25]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 100000)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [28]:
x_test

array([[ 0.41447201,  1.39501134, -0.32485683, ..., -0.479271  ,
        -0.38273877,  0.50994173],
       [-0.59207067, -1.40798236, -0.32485683, ..., -0.479271  ,
        -0.38273877,  0.50994173],
       [ 1.0016219 , -1.09653861,  1.28715495, ...,  0.2263194 ,
         0.09794496, -1.54547322],
       ...,
       [ 0.07895778, -1.09653861, -1.9368686 , ..., -0.479271  ,
        -0.38273877,  0.50994173],
       [-0.75982778,  1.39501134,  1.28715495, ..., -0.479271  ,
        -0.38273877,  0.50994173],
       [-0.67594923, -0.16220738,  1.28715495, ...,  0.82659781,
         1.05931242, -1.54547322]])

In [29]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\Varun\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
ypred = logreg.predict(x_test)

In [31]:
ypred

array([0, 1, 1, ..., 0, 0, 1])

In [32]:
y_test

array([0, 1, 1, ..., 1, 0, 1])

In [33]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [34]:
accuracy

0.8051948051948052

In [35]:
ds1.head(1)

age  job  marital  education  default  balance  housing  loan  contact  \
0   41    0        1          1        0     2288        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    4      8      1021         0      0         0         3        1

In [36]:
logreg.predict([[41, 0, 1, 1, 0, 228, 1, 0, 2, 4, 8, 1021, 0,0,0,3]])

array([1])